baseURL: http://example.org/
languageCode: en-us
title: 
theme: PaperMod

params: 
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true

  homeInfoParams:
    Title: "Hello Stranger"
    Content: >
      I'm Abylay Mukhit and I like to play and create small indie games.

      - Now I work with small team of friends to make games for mobile and PC.

      - On this page I will write about the development process of past games like [STYX](https://apps.apple.com/kz/app/styx-vertical-platformer/id1587424131) and [HPB](https://apps.apple.com/kz/app/hyper-pixel-beast/id1503065407),
      and also about future projects.
      
      - Hope to see you around! 
      

      
  socialIcons:
    - name: github
      url: "https://github.com/adityatelange/hugo-PaperMod"
    - name: KoFi
      url: "https://ko-fi.com/adityatelange"
    - name: RsS
      url: "index.xml"