baseURL: https://www.oyynkuru.com/
languageCode: en-us
title: 
theme: PaperMod

menu:
  main:
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30

params: 
  disableThemeToggle: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true

  homeInfoParams:
    Title: ""
    Content: >
      Oyynkuru is a indie game studio. 

      - On this blog you will find more about the development process of past games 
      like [STYX](https://apps.apple.com/kz/app/styx-vertical-platformer/id1587424131) and 
      [HPB](https://apps.apple.com/kz/app/hyper-pixel-beast/id1503065407),
      and also about future projects. 
      
      - You can support our team by buying our games, watching our channel, and just following us. 
      
      - Check out our social media below – we’ll be hanging out and discussing the games there. 
  socialIcons:
    - name: twitter
      url: "https://twitter.com/oyynkuru/"
    - name: reddit
      url: "https://www.reddit.com/user/oyynkuru"
    - name: kofi
      url: "https://ko-fi.com/oyynkuru"